name: Deploy Targets
description: 指定されたターゲットに対してデプロイを実行します

inputs:
  filter:
    description:  デプロイ対象を絞り込むフィルタオプションのJSON配列．[]は明示的に空を指定します．
    required: false
  channel:
    description: release もしくは staging
    required: true

runs:
  using: "composite"
  steps: 
    - uses: ./.github/actions/use-repo
      with:
        context: ${{ inputs.channel }}

    - id: filter
      uses: ./.github/actions/filter-util
      with:
        task: deploy
        filter: ${{ inputs.filter }}
    
    - name: デプロイアーティファクトのビルド
      id: build
      if: ${{ steps.filter.outputs.has_hit == 'true' }}
      shell: bash
      env:
        FILTER: ${{ steps.filter.outputs.deps_args }}
        DEPLOY_CHANNEL: ${{ inputs.channel }}
      run: |
        mapfile -t args < <(node -e 'JSON.parse(process.env.FILTER).forEach(arg => console.log(arg))')
        pnpm install --frozen-lockfile --prefer-offline --no-optimistic-repeat-install "${args[@]}"
        pnpm sync "${args[@]}"
        pnpm exec turbo run build "${args[@]}"

    - name: デプロイの実行
      id: deploy
      if: ${{ steps.filter.outputs.has_hit == 'true' }}
      shell: bash
      env:
        TARGETS: ${{ steps.filter.outputs.direct_args }}
      run: |
        mapfile -t args < <(node -e 'JSON.parse(process.env.TARGETS).forEach(arg => console.log(arg))')
        pnpm exec turbo run deploy "${args[@]}" --continue=always
