name: Turboフィルターの絞り込み
description: 特定のタスクに一致するようにTurboフィルターを絞り込み、直接タスクおよび依存タスクの引数を出力します。
inputs:
  task:
    description: 対象のTurboタスク名
    required: true
  filter:
    description: 絞り込み対象のTurboフィルター
    default: ""
outputs:
  packages:
    description: 絞り込まれたパッケージ名のJSON配列
  direct_args:
    description: 絞り込まれたパッケージ群を指定するフィルタオプションのJSON配列
  deps_args:
    description: 絞り込まれたパッケージが依存するパッケージ群を指定するフィルタオプションのJSON配列
  has_hit:
    description: 条件を満たすパッケージが一つ以上存在するか
runs:
  using: node24
  main: refine-filter.mjs
