envs:
  staging:
    SELF: https://dummy-preview-web-staging.nushinkan2.workers.dev
  release:
    SELF: https://dummy-preview-web-release.nushinkan2.workers.dev
connections:
  bindings:
    DUMMY_PREVIEW_API: "@repo/dummy-preview-api"
  urls:
    SELF: "@repo/dummy-preview-web"
reviewEntry: true
