envs:
  staging:
    SELF: https://dummy-preview-api-staging.nushinkan2.workers.dev
  release:
    SELF: https://dummy-preview-api-release.nushinkan2.workers.dev
connections:
  bindings: {}
  urls:
    SELF: "@repo/dummy-preview-api"
reviewEntry: false
