name: Deploy Release By Tag

on:
  push:
    tags:
      - release

jobs:
  deploy:
    uses: ./.github/workflows/deploy-by-tag.yml
    secrets: inherit
    with:
      base_sha: ${{ github.event.before }}
      tag_name: release