name: Heavy Tests

on:
  workflow_call:
    inputs:
      affected:
        description: Indicates if there are changes in the affected apps.
        required: true
        type: boolean
      packages:
        description: JSON package/path array from deployment plan
        required: true
        type: string
      head_sha:
        description: Fixed target SHA
        required: true
        type: string

jobs:
  ui_test:
    name: UI test
    if: ${{ inputs.affected }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.head_sha }}

      - name: Common Setup
        uses: ./.github/actions/setup
        with:
          cache_channel: "test"
          turbo_cache: "update"

      - name: Install Playwright Browsers
        run: pnpm --filter @repo/dummy-preview-web exec playwright install --with-deps

      - name: Run UI test tests
        env:
          PACKAGES: ${{ inputs.packages }}
        run: pnpm exec tsx .github/scripts/deploy/ci.ts ui_test

      - name: Collect UI test Reports
        run: pnpm tsx ./.github/scripts/collect-ui_test-reports.ts

      - name: upload UI test Reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ui_test-reports
          path: ui_test-reports
