name: Light Tests

on:
  workflow_call:
    inputs:
      affected:
        description: Indicates if there are changes in the affected apps.
        required: true
        type: boolean
      filter_args:
        description: The filter option arguments for turbo command, it contains all of affected apps.
        required: true
        type: string

jobs:
  lint:
    name: Lint
    if: ${{ inputs.affected }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Common Setup
        uses: ./.github/actions/setup
        with:
          checkout: 'shallow'
          cache_channel: 'test'
          turbo_cache: 'readonly'
      
      - name: Run Lint
        env:
          FILTER_ARGS: ${{ inputs.filter_args }}
        run: pnpm lint ${{ FILTER_ARGS }}
    
  unit:
    name: Unit Tests
    if: ${{ inputs.affected }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Common Setup
        uses: ./.github/actions/setup
        with:
          checkout: 'shallow'
          cache_channel: 'test'
          turbo_cache: 'update'
      
      - name: Run Unit Tests
        env:
          FILTER_ARGS: ${{ inputs.filter_args }}
        run: pnpm test ${{ FILTER_ARGS }}