name: Light Tests

on:
  workflow_call:
    inputs:
      affected:
        description: Indicates if there are changes in the affected apps.
        required: true
        type: boolean
      packages:
        description: JSON package/path array from deployment plan
        required: true
        type: string
      head_sha:
        description: Fixed target SHA
        required: true
        type: string

jobs:
  lint:
    name: Lint
    if: ${{ inputs.affected }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.head_sha }}

      - name: Common Setup
        uses: ./.github/actions/setup
        with:
          cache_channel: "test"
          turbo_cache: "readonly"

      - name: Run Lint
        env:
          PACKAGES: ${{ inputs.packages }}
        run: pnpm exec tsx .github/scripts/deploy/ci.ts lint
