name: Full Deploy
on:
  workflow_call:
    inputs:
      head_sha:
        description: デプロイ対象コミットのハッシュ値
        type: string
        required: true
      channel:
        description: staging または release
        type: string
        required: true
permissions:
  contents: read
concurrency:
  group: deploy-channel-${{ inputs.channel }}
  queue: max
  cancel-in-progress: false
env:
  HEAD_SHA: ${{ inputs.head_sha }}
  CHANNEL: ${{ inputs.channel }}
jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: 入力値の検証
        env:
          CHANNEL: ${{ env.CHANNEL }}
        run: '[[ "$CHANNEL" == staging || "$CHANNEL" == release ]]'
  full-deploy:
    needs: validate-inputs
    runs-on: ubuntu-latest
    environment: ${{ inputs.channel }}
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ env.HEAD_SHA }}
          persist-credentials: false
      - uses: ./.github/actions/use-repo
        with:
          context: ${{ env.CHANNEL }}
      - parallel:
        - id: unit-tests
          uses: ./.github/actions/vi-test
        - id: ui-tests
          uses: ./.github/actions/ui-test
        - id: lint
          uses: ./.github/actions/lint
      - name: デプロイの実行
        uses: ./.github/actions/deploy
        with:
          channel: ${{ env.CHANNEL }}